# Generated by Django 5.1.7 on 2025-04-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain_app', '0003_category_goods_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
