# Generated by Django 5.1.7 on 2025-04-16 07:07

import django.db.models.deletion
import supply_chain_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain_app', '0012_remove_category_user_remove_customer_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=supply_chain_app.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='categories_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=supply_chain_app.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='customers_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(default=supply_chain_app.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='goods_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='supply_chain_app.category'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='supply_chain_app.customer'),
        ),
    ]
